name             'howst'
maintainer       'Bowst'
maintainer_email 'ben@bowst.com'
license          'All rights reserved'
description      'Installs/Configures Drupal'
long_description 'Installs/Configures Drupal'
version          '0.0.1'

depends 'apt'
depends 'ohai'
depends 'mysql', '~> 6.0'
depends 'php'
depends 'nginx'
depends 'tar', '~> 0.6.0'
depends 'database', '~> 3.0.2'